// Hartford, CT social services resources — compiled via web research April 2026
export const coreResources = [
  // ===== HOUSING =====
  {
    name: 'South Park Inn - Emergency Shelter',
    organization: 'South Park Inn',
    description: 'Low-barrier emergency shelter providing 55 beds to men and women experiencing homelessness. Clients are assigned counselors who help with transportation, personal hygiene supplies, and finding housing. Also offers medical and behavioral respite program.',
    categories: ['housing'],
    address: '75 Main Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 724-0071',
    website: 'https://www.southparkinn.org',
    hours: '24/7, 365 days/year',
    eligibility: {},
    howToApply: 'Walk in or call 211 and press #3 then #1 for homeless services.',
    source: 'web-research'
  },
  {
    name: 'Open Hearth Association - Emergency Shelter',
    organization: 'Open Hearth Association',
    description: 'Oldest continuously operating shelter on the East Coast, founded in 1884. Provides 25 emergency beds for men, plus an 84-bed transitional living program with addiction recovery support, life skills training, and career planning.',
    categories: ['housing'],
    address: '437 Sheldon Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 525-3447',
    website: 'https://www.theopenhearthassoc.org',
    hours: 'Emergency shelter: 3:30 PM - 7:00 AM, 365 days/year',
    eligibility: { populations: ['men'] },
    howToApply: 'Walk in during shelter hours. Must pursue education or work for transitional program.',
    source: 'web-research'
  },
  {
    name: 'Interval House - Domestic Violence Shelter',
    organization: 'Interval House',
    description: 'Largest domestic violence agency in Connecticut, serving survivors since 1977. Provides up to 6 weeks of emergency housing for battered women and children, counseling, safety planning, court advocacy, and support groups.',
    categories: ['housing'],
    address: 'Confidential location (Hartford area)',
    city: 'Hartford',
    state: 'CT',
    zip: '06134',
    phone: '(860) 838-8467',
    website: 'https://intervalhousect.org',
    hours: '24/7 hotline: 1-888-774-2900',
    eligibility: { populations: ['domestic_violence_survivors'] },
    howToApply: 'Call the 24-hour hotline at 1-888-774-2900. All services are free and confidential.',
    source: 'web-research'
  },
  {
    name: 'CRT McKinney Shelter',
    organization: 'Community Renewal Team',
    description: 'Overnight emergency shelter for adult males with 88 beds. Provides case management, counseling, referrals, and medical day services.',
    categories: ['housing'],
    address: '34 Huyshope Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 722-6920',
    website: 'https://www.crtct.org',
    hours: '4:00 PM - 8:00 AM, 7 days/week',
    eligibility: { populations: ['men'], minAge: 18 },
    howToApply: 'Walk in during shelter hours. Hartford residents preferred.',
    source: 'web-research'
  },
  {
    name: 'YWCA Hartford - Soromundi Commons',
    organization: 'YWCA Hartford Region',
    description: 'Emergency shelter for pregnant women and single women (up to 3 months), plus transitional housing for single adults (up to 2 years). Includes efficiency units and one-bedroom apartments with supportive services.',
    categories: ['housing'],
    address: '135 Broad Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 727-0645',
    website: 'https://www.ywcahartford.org',
    hours: '24/7 for residents',
    eligibility: { populations: ['women'], minAge: 18 },
    howToApply: 'Call for intake. Must be homeless, working 20+ hours/week, and have income source for transitional housing.',
    source: 'web-research'
  },
  {
    name: 'Salvation Army - Marshall House Family Shelter',
    organization: 'The Salvation Army',
    description: 'Emergency shelter for single women and families with 27 beds, plus 2-year transitional housing program for homeless heads of household with minor children.',
    categories: ['housing'],
    address: '225 South Marshall Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 543-8423',
    website: 'https://easternusa.salvationarmy.org/southern-new-england/hartford/',
    hours: '24/7 for residents',
    eligibility: { populations: ['families', 'women'] },
    howToApply: 'Call for availability. Transitional program requires steady income and 60+ days sober.',
    source: 'web-research'
  },
  {
    name: 'Housing Authority of the City of Hartford',
    organization: 'HACH',
    description: 'Public housing and Section 8 Housing Choice Vouchers for very low-income families, elderly, and disabled individuals. Manages multiple properties including Betty Knox Apartments, Charter Oak Terrace, Smith Tower, and others.',
    categories: ['housing'],
    address: '180 Overlook Terrace',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 723-8400',
    website: 'https://www.hartfordhousing.org',
    hours: 'Mon-Fri 8:30am-4:30pm',
    eligibility: { incomeLimitPctFpl: 80 },
    howToApply: 'Apply through the Housing Authority. Income may not exceed 50% of area median income. Waitlist may apply.',
    source: 'web-research'
  },
  {
    name: 'Mercy Housing and Shelter - Shepherd House',
    organization: 'Mercy Housing and Shelter Corporation',
    description: '70-bed shelter providing meals, clothing, personal necessities, day shelter services, healthcare access, social work, and nursing services. Also operates transitional housing for people living with HIV/AIDS.',
    categories: ['housing'],
    address: '211 Wethersfield Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06114',
    phone: '(860) 808-2040',
    website: 'https://www.mercyhousingct.org',
    hours: 'Mon-Fri 8:30am-4:30pm',
    eligibility: {},
    howToApply: 'Walk in or call for intake assessment.',
    source: 'web-research'
  },
  {
    name: 'Hands On Hartford - Supportive Housing',
    organization: 'Hands On Hartford',
    description: 'Safe, affordable housing and supportive services for individuals with complex health issues. Also provides homeless outreach team connecting individuals living outdoors with resources to secure stable housing.',
    categories: ['housing'],
    address: '55 Bartholomew Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 728-3201',
    website: 'https://handsonhartford.org',
    hours: 'Day program: Mon 9am-7pm; Tue-Thu 9am-2:30pm',
    eligibility: {},
    howToApply: 'Visit the day program or call for referral. Outreach team works with people living outdoors.',
    source: 'web-research'
  },
  {
    name: 'Housing Education Resource Center',
    organization: 'Housing Education Resource Center',
    description: 'HUD-approved housing counseling agency offering pre-purchase workshops, budget counseling, rental assistance, and homeless services assistance. Services available in English and Spanish.',
    categories: ['housing'],
    address: '901 Wethersfield Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06114',
    phone: '(860) 296-4242',
    website: 'https://www.hercct.org',
    hours: 'Mon-Fri 9am-5pm',
    eligibility: {},
    howToApply: 'Call to schedule a housing counseling appointment.',
    source: 'web-research'
  },

  // ===== FOOD =====
  {
    name: 'Hands On Hartford - MANNA Community Pantry',
    organization: 'Hands On Hartford',
    description: 'Full-choice shopping model food pantry where families can grab a cart and walk through aisles, choosing items that fit their needs. Also operates a soup kitchen serving free dinner on Mondays at 5:30pm.',
    categories: ['food'],
    address: '55 Bartholomew Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 728-3201',
    website: 'https://handsonhartford.org',
    hours: 'Pantry: Mon-Thu 9am-5pm, Fri 9am-2pm (closed 12-1pm). Soup Kitchen: Mon 5:30pm.',
    eligibility: {},
    howToApply: 'Walk in during hours. Hartford residents. Appointment required for advocacy services.',
    source: 'web-research'
  },
  {
    name: 'Foodshare',
    organization: 'Connecticut Foodshare',
    description: 'Regional food bank operating mobile food distributions at 20+ Hartford locations on a rotating biweekly basis, providing free fresh produce and pantry items. No ID required at mobile sites.',
    categories: ['food'],
    address: '450 Woodland Avenue',
    city: 'Bloomfield',
    state: 'CT',
    zip: '06002',
    phone: '(860) 286-9999',
    website: 'https://www.ctfoodshare.org',
    hours: 'Mobile sites rotate biweekly at various Hartford locations. Check website for schedule.',
    eligibility: {},
    howToApply: 'Walk up to any mobile distribution site. No ID or proof of income required.',
    source: 'web-research'
  },
  {
    name: 'Salvation Army - Food Pantry',
    organization: 'The Salvation Army',
    description: 'Food pantry serving working families, laid-off workers, shelter residents, SSI/Social Security recipients, elderly, and pregnant teens. Also provides energy and rental assistance.',
    categories: ['food'],
    address: '217 Washington Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 543-8413',
    website: 'https://easternusa.salvationarmy.org/southern-new-england/hartford/',
    hours: 'Mon-Fri 8:30am-4pm',
    eligibility: {},
    howToApply: 'Walk in with photo ID, proof of address, Social Security cards, and birth certificates.',
    source: 'web-research'
  },
  {
    name: 'Catholic Charities - Institute for the Hispanic Family Food Pantry',
    organization: 'Catholic Charities Archdiocese of Hartford',
    description: 'Food pantry serving Greater Hartford residents. Also provides bilingual counseling, senior services, immigration support, and emergency financial assistance.',
    categories: ['food'],
    address: '45 Wadsworth Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 527-1124',
    website: 'https://www.ccaoh.org',
    hours: 'Wed 9am-1pm, Fri 9am-11:30am',
    eligibility: {},
    howToApply: 'Walk in with photo ID, proof of address, proof of income, and Social Security cards.',
    source: 'web-research'
  },
  {
    name: 'Community Renewal Team - Food & Basic Needs',
    organization: 'Community Renewal Team',
    description: 'Three family service centers across Hartford providing emergency food, basic needs assistance, housing assessment, information and referrals, and computer access.',
    categories: ['food'],
    address: '555 Windsor Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06120',
    phone: '(860) 560-5600',
    website: 'https://www.crtct.org',
    hours: 'Mon-Fri 8am-7pm, Sat 9am-12pm. Also at 395 Wethersfield Ave and 1229 Albany Ave.',
    eligibility: {},
    howToApply: 'Walk in to any CRT Family Service Center. Hartford residents.',
    source: 'web-research'
  },
  {
    name: 'Mercy Housing - St. Elizabeth House Friendship Center',
    organization: 'Mercy Housing and Shelter Corporation',
    description: 'Day shelter serving breakfast (8am Tue-Sat) and lunch (12pm Tue-Sat) with grab-and-go bags. Also provides showers, healthcare access, social work, and nursing services.',
    categories: ['food'],
    address: '118 Main Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 808-2120',
    website: 'https://www.mercyhousingct.org',
    hours: 'Breakfast: Tue-Sat 8am. Lunch: Tue-Sat 12pm.',
    eligibility: {},
    howToApply: 'Walk in. Hartford residents. ID required.',
    source: 'web-research'
  },
  {
    name: 'CRT SNAP Outreach',
    organization: 'Community Renewal Team',
    description: 'Free assistance with SNAP (food stamps) applications. Staff help complete applications and navigate the enrollment process. Also connects to other benefits.',
    categories: ['food'],
    address: '555 Windsor Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06120',
    phone: '(860) 560-5765',
    website: 'https://www.crtct.org/programs/basic-needs/snap-outreach/',
    hours: 'Mon-Fri 8am-5pm',
    eligibility: {},
    howToApply: 'Call for appointment or walk in. All services are free and confidential.',
    source: 'web-research'
  },
  {
    name: 'Shiloh Baptist Church Soup Kitchen & Food Pantry',
    organization: 'Shiloh Baptist Church',
    description: 'Church-based food pantry providing groceries to Hartford residents. Part of a network of faith-based food assistance programs across the city.',
    categories: ['food'],
    address: '350 Albany Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06120',
    phone: '(860) 247-3767',
    website: '',
    hours: 'Tue & Thu 12-2pm',
    eligibility: {},
    howToApply: 'Walk in during distribution hours.',
    source: 'web-research'
  },

  // ===== CASH =====
  {
    name: 'CT Department of Social Services - Hartford Office (TFA/TANF)',
    organization: 'CT Department of Social Services',
    description: 'Temporary Family Assistance (TFA) provides cash aid to families with children to help pay for basic needs while in school, job training, or during hardship. Also processes SNAP, Medicaid, and other benefits.',
    categories: ['cash'],
    address: '25 Sigourney Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 424-4908',
    website: 'https://portal.ct.gov/dss',
    hours: 'Mon-Fri 8am-5pm',
    eligibility: { populations: ['families_with_children'], incomeLimitPctFpl: 55 },
    howToApply: 'Apply online at connect.ct.gov, by phone at 1-855-626-6632, or visit the office.',
    source: 'web-research'
  },
  {
    name: 'CRT Energy Assistance (CEAP/LIHEAP)',
    organization: 'Community Renewal Team',
    description: 'Connecticut Energy Assistance Program helps low and middle-income renters and homeowners pay heating bills. Benefits paid directly to utility company or fuel vendor. Income limits: $47,764 (1 person) up to $126,758 (7+ people).',
    categories: ['cash', 'utilities'],
    address: '395 Wethersfield Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06114',
    phone: '(860) 560-5800',
    website: 'https://www.crtct.org/programs/basic-needs/energy-assistance/',
    hours: 'Mon-Fri 8am-5pm, Sat 8am-4pm. Applications: Sept 1 - May 29.',
    eligibility: {},
    howToApply: 'Apply online at ct.gov/heatinghelp, by phone at 860-560-5800, by email at crtenergyapplication@crtct.org, or visit the office.',
    source: 'web-research'
  },
  {
    name: 'Salvation Army - Emergency Financial Assistance',
    organization: 'The Salvation Army',
    description: 'Emergency financial assistance including help with rent, utilities, and other basic needs. Assistance coupled with case management to address underlying needs.',
    categories: ['cash'],
    address: '217 Washington Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 543-8413',
    website: 'https://easternusa.salvationarmy.org/southern-new-england/hartford/',
    hours: 'Mon-Fri 8:30am-4pm',
    eligibility: {},
    howToApply: 'Walk in or call for appointment. Bring photo ID and documentation of need.',
    source: 'web-research'
  },
  {
    name: 'Catholic Charities - Emergency Assistance',
    organization: 'Catholic Charities Archdiocese of Hartford',
    description: 'Emergency assistance including food, clothing, diapers, help paying rent and utilities, case management, employment services, and advocacy.',
    categories: ['cash'],
    address: '896 Asylum Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 522-8241',
    website: 'https://www.ccaoh.org',
    hours: 'Mon 1-4pm (food pantry). Call for emergency assistance hours.',
    eligibility: {},
    howToApply: 'Walk in with picture ID, proof of address, and proof of income.',
    source: 'web-research'
  },

  // ===== HARM REDUCTION =====
  {
    name: 'Connecticut Harm Reduction Alliance - The Hub',
    organization: 'Connecticut Harm Reduction Alliance (CTHRA)',
    description: 'Drop-in center providing syringe services (1.1M+ sterile syringes distributed in 2024), naloxone distribution (4,379 kits in 2024), fentanyl test strips, drug checking, safe use kits, overdose prevention training, and clinical services.',
    categories: ['harm-reduction'],
    address: '28 Grand Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 263-8720',
    website: 'https://www.ghhrc.org',
    hours: 'Call for current hours',
    eligibility: {},
    howToApply: 'Walk in. No ID or insurance required. All services are free.',
    source: 'web-research'
  },
  {
    name: 'Connecticut Harm Reduction Alliance - The Drop',
    organization: 'Connecticut Harm Reduction Alliance (CTHRA)',
    description: 'Drop-in center and harm reduction hub on Albany Avenue. Provides syringe services, naloxone, fentanyl test strips, RN outreach, and mobile outreach teams covering Hartford neighborhoods.',
    categories: ['harm-reduction'],
    address: '557-559 Albany Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06112',
    phone: '(860) 263-8720',
    website: 'https://www.ghhrc.org',
    hours: 'Call for current hours',
    eligibility: {},
    howToApply: 'Walk in. Mobile van also operates in North and South End neighborhoods 5 days/week.',
    source: 'web-research'
  },
  {
    name: 'CTHRA Mobile Outreach / Frontlines',
    organization: 'Connecticut Harm Reduction Alliance (CTHRA)',
    description: 'Street-based outreach team providing harm reduction supplies, naloxone, drug treatment referrals, and connections to services directly in Hartford neighborhoods. Mobile van removes 200,000+ used needles from streets annually.',
    categories: ['harm-reduction'],
    address: 'Mobile - operates across Hartford',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 770-7090',
    website: 'https://www.ghhrc.org/services',
    hours: 'Mon-Fri, morning and afternoon hours in North and South End neighborhoods',
    eligibility: {},
    howToApply: 'Flag down the mobile van or call Sara Piatti (Director) at 860-770-7090.',
    source: 'web-research'
  },
  {
    name: 'InterCommunity - Addiction Recovery Services',
    organization: 'InterCommunity Health Care',
    description: 'Outpatient substance use treatment including medication-assisted treatment (MAT), Low-Dose Buprenorphine Induction (LDBI) program, individual and group counseling, and recovery support services.',
    categories: ['harm-reduction'],
    address: '40 Coventry Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06112',
    phone: '(860) 569-5900',
    website: 'https://www.intercommunityct.org/addiction-recovery-services',
    hours: 'Mon-Fri 7am-5:30pm',
    eligibility: {},
    howToApply: 'Call 860-569-5900 for intake. Same-day appointments available. Accepts all insurance with sliding fee scale.',
    source: 'web-research'
  },

  // ===== HEALTHCARE =====
  {
    name: 'Charter Oak Health Center',
    organization: 'Charter Oak Health Center',
    description: 'Federally qualified health center (FQHC) providing primary care, dental care, eye care, urgent care, and behavioral health services since 1978. Joint Commission accredited. Sliding fee scale regardless of ability to pay.',
    categories: ['healthcare'],
    address: '21 Grand Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 550-7500',
    website: 'https://thecharteroak.org',
    hours: 'Mon-Thu 8am-8pm, Fri-Sat 8:30am-5pm. Urgent Care 7 days/week.',
    eligibility: {},
    howToApply: 'Call to schedule or walk in for urgent care. Sliding fee scale - no one turned away for inability to pay.',
    source: 'web-research'
  },
  {
    name: 'Community Health Services',
    organization: 'Community Health Services, Inc.',
    description: 'Federally qualified health center with two Hartford-area locations providing primary care, dental, behavioral health, and 24/7 provider coverage. Serves all patients regardless of insurance or ability to pay.',
    categories: ['healthcare'],
    address: '500 Albany Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06120',
    phone: '(860) 249-9625',
    website: 'https://www.chshartford.org',
    hours: 'Call for hours. 24/7 provider phone coverage.',
    eligibility: {},
    howToApply: 'Call main number to schedule. Sliding fee scale available.',
    source: 'web-research'
  },
  {
    name: 'Malta House of Care - Mobile Medical Clinic',
    organization: 'Malta House of Care',
    description: 'Free mobile medical clinic providing primary healthcare, physicals, testing, immunizations, medications, and health coaching to uninsured adults. Walk-in only, no appointment needed.',
    categories: ['healthcare'],
    address: '136 Farmington Avenue (Tue & Wed); 10 Campfield Avenue (Thu)',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 725-0171',
    website: 'https://maltahouseofcare.org',
    hours: 'Tue & Wed 11:45am-3:30pm at Farmington Ave; Thu 11:45am-3:30pm at Campfield Ave',
    eligibility: { populations: ['uninsured'] },
    howToApply: 'Walk in at any scheduled location. No appointment needed. Free for uninsured adults.',
    source: 'web-research'
  },
  {
    name: 'Wheeler Family Health & Wellness Center',
    organization: 'Wheeler Clinic',
    description: 'Federally qualified health center providing integrated primary and behavioral health care including screening and treatment for asthma, diabetes, high blood pressure, and mental health conditions.',
    categories: ['healthcare'],
    address: '43 Woodland Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 793-3500',
    website: 'https://www.wheelerclinic.org',
    hours: 'Mon-Fri, call for specific hours',
    eligibility: {},
    howToApply: 'Call to schedule. Sliding fee scale available.',
    source: 'web-research'
  },
  {
    name: 'Access Health CT - HUSKY Health Enrollment',
    organization: 'Access Health CT',
    description: 'Connecticut health insurance marketplace for Medicaid (HUSKY A/B/C/D) enrollment and subsidized health plans. HUSKY covers children, parents, pregnant individuals, seniors, disabled adults, and low-income adults.',
    categories: ['healthcare'],
    address: 'Phone/online enrollment',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '1-855-805-4325',
    website: 'https://www.accesshealthct.com',
    hours: 'Mon-Fri 8am-4pm (phone)',
    eligibility: {},
    howToApply: 'Apply online at accesshealthct.com, by phone at 1-855-805-4325, or at the DSS office at 25 Sigourney Street.',
    source: 'web-research'
  },
  {
    name: 'CHC at Connecticut Children\'s',
    organization: 'Community Health Center, Inc.',
    description: 'Team-based pediatric care including medical, dental, and counseling services for children. Federally qualified health center providing comprehensive care regardless of insurance.',
    categories: ['healthcare'],
    address: '282 Washington Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 547-0970',
    website: 'https://www.chc1.com',
    hours: 'Mon-Fri, call for specific hours',
    eligibility: { populations: ['children'] },
    howToApply: 'Call to schedule an appointment. Accepts all insurance with sliding fee scale.',
    source: 'web-research'
  },

  // ===== MENTAL HEALTH =====
  {
    name: 'Capitol Region Mental Health Center',
    organization: 'CT DMHAS',
    description: 'State-operated community mental health center providing outpatient psychiatric treatment, mobile crisis team, case management, and community support for adults with serious mental illness or co-occurring disorders.',
    categories: ['mental-health'],
    address: '51 Coventry Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06112',
    phone: '(860) 297-0800',
    website: 'https://portal.ct.gov/dmhas/crmhc',
    hours: 'Mon-Fri 8am-4:30pm. Mobile Crisis: Mon-Fri 8am-8:30pm at (860) 297-0999.',
    eligibility: {},
    howToApply: 'Call Intake/Referral at (860) 293-6363. For crisis, call Mobile Crisis Team at (860) 297-0999.',
    source: 'web-research'
  },
  {
    name: 'InterCommunity - Mental Health Services',
    organization: 'InterCommunity Health Care',
    description: 'Affordable behavioral health services including individual and group counseling, psychiatry, child/adolescent/family therapy, crisis stabilization, and intensive outpatient. Bilingual (Spanish) clinicians available. Same-day access.',
    categories: ['mental-health'],
    address: '40 Coventry Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06112',
    phone: '(860) 569-5900',
    website: 'https://www.intercommunityct.org',
    hours: 'Mon-Fri 7am-5:30pm (Hartford). Same-day appointments available.',
    eligibility: {},
    howToApply: 'Call 860-569-5900. Accepts all insurance. Sliding fee scale - no one denied for inability to pay.',
    source: 'web-research'
  },
  {
    name: 'The Village for Families & Children',
    organization: 'The Village for Families & Children',
    description: '44 programs including behavioral health for children and adults, substance use treatment, urgent crisis center for youth (no appointment needed), foster care, early childhood development, and family support services.',
    categories: ['mental-health'],
    address: '331 Wethersfield Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06114',
    phone: '(860) 236-4511',
    website: 'https://thevillage.org',
    hours: 'Mon-Fri 8am-5pm (extended to 7pm weekdays except Fri)',
    eligibility: {},
    howToApply: 'Call main number or walk in to Urgent Crisis Center (no referral needed for youth crisis).',
    source: 'web-research'
  },
  {
    name: 'NAMI Connecticut',
    organization: 'National Alliance on Mental Illness - Connecticut',
    description: 'Over 40 free support groups statewide for families, individuals living with mental illness, and young adults. Provides education, peer support, and advocacy. Young Adult Connection Groups available.',
    categories: ['mental-health'],
    address: '1030 New Britain Avenue, Suite 201',
    city: 'West Hartford',
    state: 'CT',
    zip: '06110',
    phone: '(860) 882-0236',
    website: 'https://namict.org',
    hours: 'Support groups meet on various schedules. Check website for Hartford-area group times.',
    eligibility: {},
    howToApply: 'Visit namict.org for support group schedule. For crisis: call CT Action Line at 1-800-467-3135.',
    source: 'web-research'
  },
  {
    name: '988 Suicide & Crisis Lifeline (Connecticut)',
    organization: 'United Way 211 / SAMHSA',
    description: '24/7 crisis support for anyone experiencing suicidal thoughts, substance use crises, or emotional distress. Connects to trained crisis counselors. In Connecticut, also links to CT Mobile Crisis Intervention via 211.',
    categories: ['mental-health'],
    address: 'Phone service',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '988',
    website: 'https://988lifeline.org',
    hours: '24/7/365',
    eligibility: {},
    howToApply: 'Call or text 988. For CT Mobile Crisis, call 211.',
    source: 'web-research'
  },

  // ===== EMPLOYMENT =====
  {
    name: 'Hartford American Job Center',
    organization: 'Capital Workforce Partners / CT Department of Labor',
    description: 'Free career services including job search assistance, resume writing, interview preparation, skills training, and employer connections. Part of the statewide American Job Center network.',
    categories: ['employment'],
    address: '3580 Main Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06120',
    phone: '(860) 256-3700',
    website: 'https://capitalworkforce.org/american-job-centers/',
    hours: 'Also at Hartford Public Library (500 Main St): Tue & Thu 10am-3pm',
    eligibility: {},
    howToApply: 'Walk in or call (860) 406-3374. Services are free and available in person and virtually.',
    source: 'web-research'
  },
  {
    name: 'Capital Workforce Partners',
    organization: 'Capital Workforce Partners',
    description: 'Regional Workforce Development Board for North Central Connecticut. Connects job seekers with training and career opportunities. Coordinates youth employment programs and employer partnerships.',
    categories: ['employment'],
    address: '1 Union Place',
    city: 'Hartford',
    state: 'CT',
    zip: '06103',
    phone: '(860) 522-1111',
    website: 'https://capitalworkforce.org',
    hours: 'Mon-Fri 8:30am-5pm',
    eligibility: {},
    howToApply: 'Visit capitalworkforce.org or call for program information.',
    source: 'web-research'
  },
  {
    name: 'Hartford Job Corps Center',
    organization: 'U.S. Department of Labor',
    description: 'Free career training and education for low-income youth ages 16-24. Provides hands-on training in fields including Clinical Medical Assistant and Insurance/Financial Services, plus housing and meals.',
    categories: ['employment'],
    address: '100 William Shorty Campbell Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 952-1704',
    website: 'https://hartford.jobcorps.gov',
    hours: 'Residential program',
    eligibility: { minAge: 16, maxAge: 24 },
    howToApply: 'Call 800-733-5627 or fill out interest form at MyJobCorps. Completely free, federally funded.',
    source: 'web-research'
  },
  {
    name: 'CT State Community College - Workforce Development',
    organization: 'CT State Community College',
    description: 'Short-term licensure and certificate training programs for individuals re-entering the workforce or acquiring new skills. Affordable tuition with financial aid available.',
    categories: ['employment'],
    address: '950 Main Street, Room 208',
    city: 'Hartford',
    state: 'CT',
    zip: '06103',
    phone: '(860) 906-5130',
    website: 'https://ctstate.edu/workforce-development/wdce',
    hours: 'Mon-Fri, call for specific hours',
    eligibility: {},
    howToApply: 'Call or visit the campus to register. Financial aid available.',
    source: 'web-research'
  },

  // ===== CHILDCARE =====
  {
    name: 'CREC Head Start',
    organization: 'Capitol Region Education Council (CREC)',
    description: 'Free early childhood education for children birth to 5 years and their families throughout Hartford County. Over 300 children served in partnership with The Village for Families and Children.',
    categories: ['childcare'],
    address: '111 Charter Oak Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 247-2732',
    website: 'https://www.crec.org/head-start/',
    hours: 'Full-day program, school year schedule',
    eligibility: { populations: ['children_0_5'] },
    howToApply: 'Call CREC Central at 860-247-CREC. Eligibility based on federal Head Start income guidelines.',
    source: 'web-research'
  },
  {
    name: 'Hartford Early Learning Centers',
    organization: 'City of Hartford',
    description: 'City-operated early learning centers providing affordable childcare and school readiness programs for Hartford children.',
    categories: ['childcare'],
    address: 'Multiple Hartford locations',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 757-9500',
    website: 'https://www.hartfordct.gov/Government/Departments/DFCY/DFCY_Early-Learning/DFCY_HtfdELC',
    hours: 'Full-day program, Mon-Fri',
    eligibility: { populations: ['children'] },
    howToApply: 'Visit the city website or call for application and locations.',
    source: 'web-research'
  },
  {
    name: 'YWCA Kidslink Before & After School Program',
    organization: 'YWCA Hartford Region',
    description: 'Quality before and after school care for students in grades K-5. Accepts Care4Kids subsidized childcare to help with costs.',
    categories: ['childcare'],
    address: '135 Broad Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 525-1163',
    website: 'https://www.ywcahartford.org/programs/childcare/kidslink-before-after-school-program/',
    hours: 'Before school: 7am-start; After school: dismissal-6pm',
    eligibility: { populations: ['children_k_5'] },
    howToApply: 'Call or visit website. Accepts Care4Kids subsidized childcare payments.',
    source: 'web-research'
  },
  {
    name: 'Catholic Charities - Early Head Start & School Readiness',
    organization: 'Catholic Charities Archdiocese of Hartford',
    description: 'Accredited, affordable full-day childcare and school readiness programs for infants, toddlers, and pre-K (ages 3-5). Comprehensive family support services included.',
    categories: ['childcare'],
    address: '896 Asylum Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 934-8047',
    website: 'https://www.ccaoh.org/how-we-help/children-youth/',
    hours: 'Full-day, full-year program',
    eligibility: { populations: ['children_0_5'] },
    howToApply: 'Call 860-934-8047 to learn about enrollment and eligibility.',
    source: 'web-research'
  },

  // ===== LEGAL =====
  {
    name: 'Greater Hartford Legal Aid',
    organization: 'Greater Hartford Legal Aid, Inc.',
    description: 'Free civil legal services for low-income people and seniors in 24 Greater Hartford towns. Handles housing/eviction, public benefits, family law, immigration, disability, and elder law cases.',
    categories: ['legal'],
    address: '999 Asylum Avenue, 3rd Floor',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 541-5000',
    website: 'https://www.ghla.org',
    hours: 'Mon-Fri, call for hours',
    eligibility: { incomeLimitPctFpl: 125 },
    howToApply: 'Call 860-541-5003. Seniors 60+ can call GHLA directly. Must live near federal poverty level (~$30K for family of 4).',
    source: 'web-research'
  },
  {
    name: 'Statewide Legal Services of Connecticut',
    organization: 'Statewide Legal Services',
    description: 'Legal aid hotline connecting low-income Connecticut residents with free legal assistance. Can tell you if you qualify for a free lawyer and connect you with one in your community.',
    categories: ['legal'],
    address: 'Phone/online intake',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '1-800-453-3320',
    website: 'https://slsct.org',
    hours: 'Mon-Fri 9am-12pm, 1-2pm. Or text APPLY to 860-300-3845.',
    eligibility: { incomeLimitPctFpl: 125 },
    howToApply: 'Call 1-800-453-3320 or text APPLY to 860-300-3845. Also apply online at slsct.org.',
    source: 'web-research'
  },
  {
    name: 'Eviction Help CT - Right to Counsel',
    organization: 'Connecticut Right to Counsel Program',
    description: 'Free experienced lawyers for eligible tenants facing eviction or loss of housing subsidy (Section 8). Part of Connecticut\'s right to counsel program for tenants.',
    categories: ['legal'],
    address: 'Phone/online intake',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '1-800-559-1565',
    website: 'https://evictionhelpct.org',
    hours: 'Mon-Fri, call for hours',
    eligibility: {},
    howToApply: 'Call 1-800-559-1565 or visit evictionhelpct.org to apply for free legal representation.',
    source: 'web-research'
  },

  // ===== TRANSPORTATION =====
  {
    name: 'CTtransit Hartford',
    organization: 'Connecticut Department of Transportation',
    description: 'Public bus system serving Hartford and surrounding towns. Reduced fares for seniors (65+), Medicare cardholders, and persons with disabilities. CTpass program provides discounted passes through social service agencies.',
    categories: ['transportation'],
    address: 'Multiple routes across Hartford',
    city: 'Hartford',
    state: 'CT',
    zip: '06103',
    phone: '(860) 522-8101',
    website: 'https://www.cttransit.com',
    hours: 'Routes vary. See cttransit.com for schedules.',
    eligibility: {},
    howToApply: 'Buy passes online or at the transit center. Reduced fare: apply with $5 fee for photo ID card. Medicare cardholders show card to driver.',
    source: 'web-research'
  },
  {
    name: 'VEYO - Non-Emergency Medical Transportation (NEMT)',
    organization: 'Veyo / CT Department of Social Services',
    description: 'Free transportation to medical, behavioral health, and dental appointments for Medicaid (HUSKY) members who have no other way to get to appointments.',
    categories: ['transportation'],
    address: 'Phone service',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '1-855-478-7350',
    website: 'https://portal.ct.gov/dss/health-and-home-care/non-emergency-medical-transportation',
    hours: 'Call to schedule. Rides available for all medical appointments.',
    eligibility: { populations: ['medicaid_members'] },
    howToApply: 'Call 1-855-478-7350 to schedule a ride. Must be enrolled in CT Medicaid/HUSKY.',
    source: 'web-research'
  },

  // ===== UTILITIES =====
  {
    name: 'Generation Power CT (formerly Operation Fuel)',
    organization: 'Generation Power CT',
    description: 'One-time energy assistance grants up to $500 toward a utility bill or fuel delivery for Connecticut households struggling to pay energy costs. Opens twice per year.',
    categories: ['utilities'],
    address: 'Phone enrollment',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(860) 253-6395',
    website: 'https://operationfuel.org',
    hours: 'Call and press 1 for appointment. Seasonal availability.',
    eligibility: {},
    howToApply: 'Call (860) 253-6395 and press 1 to schedule an appointment.',
    source: 'web-research'
  },
  {
    name: 'CRT Weatherization Program',
    organization: 'Community Renewal Team',
    description: 'Free home energy efficiency improvements for income-eligible households including air sealing, insulation, heating system repairs, energy-efficient light bulbs, and hot water devices. Priority given to elderly, disabled, and families with children.',
    categories: ['utilities'],
    address: '555 Windsor Street, 2nd Floor',
    city: 'Hartford',
    state: 'CT',
    zip: '06120',
    phone: '(860) 560-4004',
    website: 'https://www.crtct.org/programs/basic-needs/weatherization-services/',
    hours: 'Mon-Fri 8am-5pm',
    eligibility: {},
    howToApply: 'Apply by fax, mail, email, or in person. Household income must be at or below 60% of state median income. Call 1-877-947-3873 for info.',
    source: 'web-research'
  },
  {
    name: 'Eversource Financial Assistance Programs',
    organization: 'Eversource Energy',
    description: 'Financial assistance for customers with past-due balances including Matching Payment Program, Electric Discount Rate, and Winter Protection (Nov 1 - May 1 shut-off protection for income-eligible customers).',
    categories: ['utilities'],
    address: 'Phone enrollment',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(800) 286-2828',
    website: 'https://www.eversource.com',
    hours: 'Mon-Fri 7am-7pm',
    eligibility: {},
    howToApply: 'Call 800-286-2828 or call CRT at 860-560-5800 for enrollment assistance.',
    source: 'web-research'
  },

  // ===== IMMIGRATION =====
  {
    name: 'Connecticut Institute for Refugees and Immigrants (CIRI) - Hartford',
    organization: 'Connecticut Institute for Refugees and Immigrants',
    description: 'DOJ-recognized immigration legal services since 1918. Handles asylum, U-visas, Special Immigrant Juvenile Status, family petitions, employment authorization, naturalization, and relief for crime survivors. Also provides refugee resettlement, workforce readiness, and adult education.',
    categories: ['immigration'],
    address: '75 Charter Oak Avenue, Suite 2-180',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '(203) 336-0141',
    website: 'https://cirict.org',
    hours: 'Mon-Fri, call for hours',
    eligibility: {},
    howToApply: 'Call for intake appointment. Affordable fees for low-income individuals. 3,186 clients served statewide in 2025.',
    source: 'web-research'
  },
  {
    name: 'Hartford Public Library - The American Place (TAP)',
    organization: 'Hartford Public Library',
    description: 'Free immigration services including citizenship classes, N-400 application assistance, legal advice from DOJ-accredited representatives, English classes, green card renewal help, and immigrant youth programs. First library-based citizenship program in the U.S.',
    categories: ['immigration'],
    address: '500 Main Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06103',
    phone: '(860) 695-6300',
    website: 'https://tap.hplct.org',
    hours: 'Mon-Thu 10am-8pm, Fri-Sat 10am-5pm',
    eligibility: {},
    howToApply: 'Visit The American Place at Hartford Public Library. All services are free.',
    source: 'web-research'
  },
  {
    name: 'Greater Hartford Legal Aid - Immigration',
    organization: 'Greater Hartford Legal Aid',
    description: 'Free immigration legal services for low-income Hartford-area residents including asylum applications, VAWA petitions, T/U-visa cases, and naturalization assistance.',
    categories: ['immigration', 'legal'],
    address: '999 Asylum Avenue, 3rd Floor',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 541-5000',
    website: 'https://www.ghla.org',
    hours: 'Mon-Fri, call for hours',
    eligibility: { incomeLimitPctFpl: 125 },
    howToApply: 'Call 860-541-5003 for intake. Must meet income eligibility.',
    source: 'web-research'
  },
  {
    name: 'Catholic Charities - Immigration & Refugee Services',
    organization: 'Catholic Charities Archdiocese of Hartford',
    description: 'Resettlement assistance, case management, legal services, and counseling for immigrants and refugees in the Hartford area.',
    categories: ['immigration'],
    address: '134 Farmington Avenue',
    city: 'Hartford',
    state: 'CT',
    zip: '06105',
    phone: '(860) 493-1841',
    website: 'https://www.ccaoh.org',
    hours: 'Mon-Fri, call for hours',
    eligibility: {},
    howToApply: 'Call for intake and appointment.',
    source: 'web-research'
  },

  // ===== ADDITIONAL CROSS-CATEGORY RESOURCES =====
  {
    name: '211 Connecticut',
    organization: 'United Way of Connecticut',
    description: 'Statewide information and referral service connecting residents to health and human services. Covers housing, food, healthcare, mental health, financial assistance, and more. Available 24/7 in multiple languages.',
    categories: ['housing', 'food', 'cash', 'healthcare', 'mental-health', 'utilities'],
    address: 'Phone/online service',
    city: 'Hartford',
    state: 'CT',
    zip: '06106',
    phone: '211',
    website: 'https://www.211ct.org',
    hours: '24/7/365. TTY: 1-800-671-0737. Outside CT: 1-800-203-1234.',
    eligibility: {},
    howToApply: 'Dial 211 from any phone. For homeless emergency, press #3 then #1.',
    source: 'web-research'
  },
  {
    name: 'Community Renewal Team (CRT) - Multi-Service Agency',
    organization: 'Community Renewal Team',
    description: 'Connecticut\'s largest community action agency providing comprehensive human services including housing, emergency shelters, food assistance, energy assistance, weatherization, childcare, youth employment, substance abuse prevention, and senior nutrition.',
    categories: ['housing', 'food', 'cash', 'utilities', 'employment', 'childcare'],
    address: '555 Windsor Street',
    city: 'Hartford',
    state: 'CT',
    zip: '06120',
    phone: '(860) 560-5600',
    website: 'https://www.crtct.org',
    hours: 'Mon-Fri 8am-5pm. Family Service Centers: Mon-Fri 8am-7pm, Sat 9am-12pm.',
    eligibility: {},
    howToApply: 'Call main line or walk in to any CRT location.',
    source: 'web-research'
  },
];


export const categorySeeds = [
  { name: 'Housing', slug: 'housing', icon: '🏠', displayOrder: 1 },
  { name: 'Food', slug: 'food', icon: '🍎', displayOrder: 2 },
  { name: 'Cash Assistance', slug: 'cash', icon: '💵', displayOrder: 3 },
  { name: 'Harm Reduction', slug: 'harm-reduction', icon: '💊', displayOrder: 4 },
  { name: 'Healthcare', slug: 'healthcare', icon: '🏥', displayOrder: 5 },
  { name: 'Mental Health', slug: 'mental-health', icon: '🧠', displayOrder: 6 },
  { name: 'Employment', slug: 'employment', icon: '💼', displayOrder: 7 },
  { name: 'Childcare', slug: 'childcare', icon: '👶', displayOrder: 8 },
  { name: 'Legal Aid', slug: 'legal', icon: '⚖️', displayOrder: 9 },
  { name: 'Transportation', slug: 'transportation', icon: '🚌', displayOrder: 10 },
  { name: 'Utilities', slug: 'utilities', icon: '💡', displayOrder: 11 },
  { name: 'Immigration', slug: 'immigration', icon: '📄', displayOrder: 12 },
]
